${p:agent/sys.file.separator}udclient, even in a coment, gives error on Windows
On Windows you can execute this command line even if you do not always use "\" as the separator:
${p:agent/GROOVY_HOME}/bin/groovy -cp ${p:agent/AGENT_HOME}/opt/udclient/udclient.jar ListApplicationprocessProperties.groovy 
but if you have the following: 

${p:agent/sys.file.separator}udclient

in a comment inside the groovy file, after replacement of the Windows file separator, groovy fails to parse "\udclient" with:

C:\Groovy\scripts>groovy  -cp D:\UCD\6.2.4.1\udclient\udclient.jar D:\UCD\6.2.4.1\agent_via_relay\var\work\RunListAllApplicationsThroughRelay\myGroovyscript.groovy
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during parsing: Did not find four digit hex character code. line: 5 col:100